version: '3.9'

services:
  shortening-gateway-service:
    image: nginx
    restart: unless-stopped
    ports:
      - 7000:80
      - 7001:443
    networks:
      shortening-network:
        ipv4_address: 182.39.0.53
        aliases:
          - shortening.local.com
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/certs:/etc/nginx/certs

  shortening-database-service:
    image: mongo
    restart: always
    ports:
      - '7002:27017'
    networks:
      shortening-network:
        ipv4_address: 182.39.0.52
        aliases:
          - shortening.database.local.com
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin-password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  shortening-cache-service:
    image: redis
    restart: always
    ports:
      - '7003:6379'
    networks:
      shortening-network:
        ipv4_address: 182.39.0.203
        aliases:
          - shortening.cache.local.com
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  shortening-api-service:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    image: shortening-api-service
    ports:
      - 7004:3000
      - 7005:9229
    networks:
        shortening-network:
          ipv4_address: 182.39.0.172
          aliases:
            - shortening.api.local.com
    restart: unless-stopped
    depends_on:
      - shortening-gateway-service
      - shortening-database-service
      - shortening-cache-service
    volumes:
    - .:/app
    - /app/node_modules
    container_name: shortening-api-service
    command: npm run start:dev

volumes:
  cache:
    driver: local

networks:
  shortening-network:
    ipam:
      driver: default
      config:
        - subnet: 182.39.0.0/16